### ISSUE TITLE
Error Message = Locale not recognized  in SQLcl 20.1

### ISSUE THREAD

**Issue by martindsouza** [martindsouza/docker-oracle-sqlcl#12]
After updating SQLcl to 20.2 getting the following error when trying to connect using SQLcl:

```
  USER          = giffy
  URL           = jdbc:oracle:thin:@localhost:32118/xepdb1
  Error Message = Locale not recognized
```

**Comment by martindsouza** [comment]
Thanks to @krisrice for suggestion. Add this to `ENV`:

`ENV LANG=“en_US.utf8”`

**Comment by martindsouza** [comment]
Fixed.

**Comment by krisrice** [comment]
FYI..  The core issue was the docker is setting ENV LANG C.UTF-8
 and starting in sqlcl 20+ the LANG is honored so this has to be overwritten to something valid.

**Comment by bamcgill** [comment]
logged a bug for this in SQLcl where we will look for POSIX and C LANG settings and set them to us english for Java
