### ISSUE TITLE
Using OCI and TNS_ADMIN getting "ORA-28759: failure to open file"

### ISSUE THREAD

**Issue by martindsouza** [martindsouza/docker-oracle-sqlcl#13]
When trying to connect to an OCI (Oracle cloud) environment with the wallet getting the following error: `ORA-28759: failure to open file`

**Comment by martindsouza** [comment]
Solution: This is in the wallet's `sqlnet.ora` file. 

Old:
`WALLET_LOCATION = (SOURCE = (METHOD = file) (METHOD_DATA = (DIRECTORY="?/network/admin")))`

New (fix):
`WALLET_LOCATION = (SOURCE = (METHOD = file) (METHOD_DATA = (DIRECTORY="$TNS_ADMIN")))`

**Comment by martindsouza** [comment]
Fixed. Did not automatically update the `sqlnet.ora` file in case user wanted other changes. Could do this in the future.

**Comment by martindsouza** [comment]
Could automate using `sed`:

```bash
sed -i .bak "s|?/network/admin|\$TNS_ADMIN|g" $TNS_ADMIN/sqlnet.ora
```

**Comment by gsilvers** [comment]
owe you guys a dollar for this one
